---
title: "Replication of Study 2 by Markowitz (2024, PNAS Nexus)"
author: "Sarah I. Segall (ssegall@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

<!-- [No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information. You will likely contact the authors of the original study, so this should be professional and forward facing. It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense. -->  

One part of my research program is to understand the psychological implications of generative AI, including how people percieve and respond to AI-generated information. I am particularly interested in whether using AI to make information more accessible changes not only people's understanding of that information but also their perceptions of its source, the author. Scientific information is one area where information may be difficult to grasp for nonexperts because the language can be complex. I therefore chose to directly replicate Markowitz's paper (2024), titled "From Complexity to Clarity: How AI Enhances Perceptions of Scientists and the Public's Understanding of Science." In Study 2, the author experimentally tested whether reading simpler AI-generated scientific summaries, rather than more complex human-written summaries, affected perceptions of scientists' credibility, trustworthiness, and intelligence. This experiment closely aligns with my broader interest in how generative AI changes people's psychological responses to information and those who communicate it.

The experiment includes five pairs of human-written PNAS significance statements and GPT-generated significance statements originally created in Study 1b. The five pairs were selected because they showed the largest differences in the use of common words. These stimulus texts are available in the supplementary materials. Each participant would be randomly assigned to three of the five stimulus pairs and, within each pair, randomly assigned to read either the GPT-generated, simpler version or the human-written, more complex PNAS version. After each text, participants would complete manipulation checks assessing its clarity, complexity, and how much of the summary they understood. They would also rate the scientist's intelligence, credibility, and trustworthiness and indicate whether they believed the summary was written by a human or by AI. The order of the measures and the items within each block would be randomized, as the original paper had done. Basic demographic information would also be collected. The entire study should take approximately 10-15 minutes.

To analyze this data and reproduce the original findings, I will employ linear mixed-effects models because each participant provides multiple observations and individual stimuli are presented to multiple participants. Futhor following Markowitz (2024), the models would include random intercepts for both participant and stimulus, with text condition (GPT/simple versus PNAS/complex) as the primary fixed effect. One anticipated challenge will be to gather enough participant data in the time frame of a few weeks, depending on the sample size from the power analysis.

Link to repo: <https://sisegall.github.io/markowitz2024/>
Linked pathway to the original paper: <https://github.com/sisegall/markowitz2024/blob/main/original_paper/Markowitz_2024_PNASNexus_AI_science_summaries.pdf> 




## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
